name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build docker image
        run: cd auth && docker build -t nzwilliammorris/auth .

      - name: Login to docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the image to dockerhub
        run: docker push nzwilliammorris/auth

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
        env:
          DOCKER_USERNAME: ${{ secrets.AWS_ACCESS_KEY_ID }}
          DOCKER_PASSWORD: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name my-eks-cluster --region ap-southeast-2

      - name: Deploy to EKS
        run: kubectl rollout restart deployment auth-depl
